const fs = require('fs');
const path = require('path');

const locales = ['en', 'de', 'es', 'nl', 'fr'];
const newKeys = {
  en: {"overview": "Overview","welcomeBack": "Welcome back","activeApplications": "Active Applications","upcomingAppointments": "Upcoming Appointments","recentEarnings": "Recent Earnings","opportunities": "Opportunities","availableCases": "Available Cases","noCases": "No available cases right now.","apply": "Apply","applied": "Applied","withdraw": "Withdraw","withdrawConfirm": "Are you sure you want to withdraw this application?","myApplications": "My Applications","noApplications": "No applications yet.","schedule": "Schedule","noAppointments": "No upcoming appointments.","earnings": "Earnings","totalEarnings": "Total Earnings","pendingPayout": "Pending Payout","completedCases": "Completed Cases","noEarnings": "No earnings yet.","profile": "Profile","editProfile": "Edit Profile","personalInfo": "Personal Information","professionalInfo": "Professional Information","serviceAndPricing": "Service & Pricing","settings": "Settings","servicePreferences": "Service Preferences","notificationPreferences": "Notification Preferences","account": "Account","offersHomeVisits": "Offers home visits","offersPracticeVisits": "Offers practice visits","practiceFee": "Practice fee","homeVisitFee": "Home visit fee"},
  de: {"overview": "Übersicht","welcomeBack": "Willkommen zurück","activeApplications": "Aktive Bewerbungen","upcomingAppointments": "Anstehende Termine","recentEarnings": "Letzte Einnahmen","opportunities": "Aufträge","availableCases": "Verfügbare Fälle","noCases": "Derzeit keine verfügbaren Fälle.","apply": "Bewerben","applied": "Beworben","withdraw": "Zurückziehen","withdrawConfirm": "Möchten Sie diese Bewerbung wirklich zurückziehen?","myApplications": "Meine Bewerbungen","noApplications": "Noch keine Bewerbungen.","schedule": "Terminplan","noAppointments": "Keine anstehenden Termine.","earnings": "Einnahmen","totalEarnings": "Gesamteinnahmen","pendingPayout": "Ausstehende Auszahlung","completedCases": "Abgeschlossene Fälle","noEarnings": "Noch keine Einnahmen.","profile": "Profil","editProfile": "Profil bearbeiten","personalInfo": "Persönliche Daten","professionalInfo": "Berufliche Informationen","serviceAndPricing": "Service & Preise","settings": "Einstellungen","servicePreferences": "Servicepräferenzen","notificationPreferences": "Benachrichtigungseinstellungen","account": "Konto","offersHomeVisits": "Bietet Hausbesuche an","offersPracticeVisits": "Bietet Praxisbesuche an","practiceFee": "Praxisgebühr","homeVisitFee": "Hausbesuchsgebühr"},
  es: {"overview": "Resumen","welcomeBack": "Bienvenido de nuevo","activeApplications": "Solicitudes activas","upcomingAppointments": "Próximas citas","recentEarnings": "Ingresos recientes","opportunities": "Oportunidades","availableCases": "Casos disponibles","noCases": "No hay casos disponibles en este momento.","apply": "Postularse","applied": "Postulado","withdraw": "Retirar","withdrawConfirm": "¿Estás seguro de que deseas retirar esta solicitud?","myApplications": "Mis solicitudes","noApplications": "Aún no hay solicitudes.","schedule": "Agenda","noAppointments": "No hay citas próximas.","earnings": "Ingresos","totalEarnings": "Ingresos totales","pendingPayout": "Pago pendiente","completedCases": "Casos completados","noEarnings": "Aún no hay ingresos.","profile": "Perfil","editProfile": "Editar perfil","personalInfo": "Información personal","professionalInfo": "Información profesional","serviceAndPricing": "Servicio y precios","settings": "Configuración","servicePreferences": "Preferencias de servicio","notificationPreferences": "Preferencias de notificación","account": "Cuenta","offersHomeVisits": "Ofrece visitas a domicilio","offersPracticeVisits": "Ofrece visitas en consulta","practiceFee": "Tarifa de consulta","homeVisitFee": "Tarifa de visita a domicilio"},
  nl: {"overview": "Overzicht","welcomeBack": "Welkom terug","activeApplications": "Actieve sollicitaties","upcomingAppointments": "Aankomende afspraken","recentEarnings": "Recente inkomsten","opportunities": "Opdrachten","availableCases": "Beschikbare cases","noCases": "Momenteel geen beschikbare cases.","apply": "Solliciteren","applied": "Gesolliciteerd","withdraw": "Intrekken","withdrawConfirm": "Weet je zeker dat je deze sollicitatie wilt intrekken?","myApplications": "Mijn sollicitaties","noApplications": "Nog geen sollicitaties.","schedule": "Planning","noAppointments": "Geen aankomende afspraken.","earnings": "Inkomsten","totalEarnings": "Totale inkomsten","pendingPayout": "Uitbetaling in afwachting","completedCases": "Voltooide cases","noEarnings": "Nog geen inkomsten.","profile": "Profiel","editProfile": "Profiel bewerken","personalInfo": "Persoonlijke gegevens","professionalInfo": "Professionele informatie","serviceAndPricing": "Service & prijzen","settings": "Instellingen","servicePreferences": "Servicevoorkeuren","notificationPreferences": "Meldingsvoorkeuren","account": "Account","offersHomeVisits": "Biedt huisbezoeken aan","offersPracticeVisits": "Biedt praktijkbezoeken aan","practiceFee": "Praktijktarief","homeVisitFee": "Huisbezoektarief"},
  fr: {"overview": "Aperçu","welcomeBack": "Bon retour","activeApplications": "Candidatures actives","upcomingAppointments": "Rendez-vous à venir","recentEarnings": "Revenus récents","opportunities": "Opportunités","availableCases": "Cas disponibles","noCases": "Aucun cas disponible pour le moment.","apply": "Postuler","applied": "Postulé","withdraw": "Retirer","withdrawConfirm": "Êtes-vous sûr de vouloir retirer cette candidature ?","myApplications": "Mes candidatures","noApplications": "Aucune candidature pour le moment.","schedule": "Planning","noAppointments": "Aucun rendez-vous à venir.","earnings": "Revenus","totalEarnings": "Revenus totaux","pendingPayout": "Paiement en attente","completedCases": "Cas terminés","noEarnings": "Aucun revenu pour le moment.","profile": "Profil","editProfile": "Modifier le profil","personalInfo": "Informations personnelles","professionalInfo": "Informations professionnelles","serviceAndPricing": "Service et tarifs","settings": "Paramètres","servicePreferences": "Préférences de service","notificationPreferences": "Préférences de notification","account": "Compte","offersHomeVisits": "Propose des visites à domicile","offersPracticeVisits": "Propose des visites au cabinet","practiceFee": "Tarif cabinet","homeVisitFee": "Tarif visite à domicile"}
};

for (const loc of locales) {
  const file = path.join(__dirname, 'messages', `${loc}.json`);
  const data = JSON.parse(fs.readFileSync(file, 'utf8'));
  data.bc = newKeys[loc];
  fs.writeFileSync(file, JSON.stringify(data, null, 2));
}
