export const COUNTRIES = [
  { code: 'DE', name: 'Deutschland', flag: '🇩🇪' },
  { code: 'AT', name: 'Österreich', flag: '🇦🇹' },
  { code: 'CH', name: 'Schweiz', flag: '🇨🇭' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'LU', name: 'Luxemburg', flag: '🇱🇺' },
  { code: 'BE', name: 'Belgien', flag: '🇧🇪' },
  { code: 'NL', name: 'Niederlande', flag: '🇳🇱' },
  { code: 'FR', name: 'Frankreich', flag: '🇫🇷' },
  { code: 'IT', name: 'Italien', flag: '🇮🇹' },
  { code: 'ES', name: 'Spanien', flag: '🇪🇸' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: 'GB', name: 'Vereinigtes Königreich', flag: '🇬🇧' },
  { code: 'IE', name: 'Irland', flag: '🇮🇪' },
  { code: 'DK', name: 'Dänemark', flag: '🇩🇰' },
  { code: 'SE', name: 'Schweden', flag: '🇸🇪' },
  { code: 'NO', name: 'Norwegen', flag: '🇳🇴' },
  { code: 'FI', name: 'Finnland', flag: '🇫🇮' },
  { code: 'PL', name: 'Polen', flag: '🇵🇱' },
  { code: 'CZ', name: 'Tschechien', flag: '🇨🇿' },
  { code: 'HU', name: 'Ungarn', flag: '🇭🇺' },
  { code: 'RO', name: 'Rumänien', flag: '🇷🇴' },
  { code: 'HR', name: 'Kroatien', flag: '🇭🇷' },
  { code: 'SI', name: 'Slowenien', flag: '🇸🇮' },
  { code: 'SK', name: 'Slowakei', flag: '🇸🇰' },
  { code: 'LT', name: 'Litauen', flag: '🇱🇹' },
  { code: 'LV', name: 'Lettland', flag: '🇱🇻' },
  { code: 'EE', name: 'Estland', flag: '🇪🇪' },
  { code: 'GR', name: 'Griechenland', flag: '🇬🇷' },
  { code: 'BG', name: 'Bulgarien', flag: '🇧🇬' },
  { code: 'CY', name: 'Zypern', flag: '🇨🇾' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹' },
  { code: 'US', name: 'Vereinigte Staaten', flag: '🇺🇸' },
  { code: 'CA', name: 'Kanada', flag: '🇨🇦' },
];

export const PHONE_PREFIXES = [
  { code: '+49', name: 'Deutschland', flag: '🇩🇪' },
  { code: '+43', name: 'Österreich', flag: '🇦🇹' },
  { code: '+41', name: 'Schweiz', flag: '🇨🇭' },
  { code: '+44', name: 'United Kingdom', flag: '🇬🇧' },
  { code: '+33', name: 'France', flag: '🇫🇷' },
  { code: '+31', name: 'Netherlands', flag: '🇳🇱' },
  { code: '+34', name: 'Spain', flag: '🇪🇸' },
  { code: '+39', name: 'Italy', flag: '🇮🇹' },
  { code: '+1', name: 'USA/Canada', flag: '🇺🇸' },
  { code: '+48', name: 'Poland', flag: '🇵🇱' },
  { code: '+45', name: 'Denmark', flag: '🇩🇰' },
  { code: '+46', name: 'Sweden', flag: '🇸🇪' },
  { code: '+47', name: 'Norway', flag: '🇳🇴' },
  { code: '+358', name: 'Finland', flag: '🇫🇮' },
  { code: '+32', name: 'Belgium', flag: '🇧🇪' },
  { code: '+352', name: 'Luxembourg', flag: '🇱🇺' },
  { code: '+351', name: 'Portugal', flag: '🇵🇹' },
  { code: '+30', name: 'Greece', flag: '🇬🇷' },
  { code: '+420', name: 'Czech Republic', flag: '🇨🇿' },
  { code: '+36', name: 'Hungary', flag: '🇭🇺' },
  { code: '+40', name: 'Romania', flag: '🇷🇴' },
  { code: '+385', name: 'Croatia', flag: '🇭🇷' },
  { code: '+386', name: 'Slovenia', flag: '🇸🇮' },
  { code: '+421', name: 'Slovakia', flag: '🇸🇰' },
  { code: '+370', name: 'Lithuania', flag: '🇱🇹' },
  { code: '+371', name: 'Latvia', flag: '🇱🇻' },
  { code: '+372', name: 'Estonia', flag: '🇪🇪' },
];
