export const SPECIALTIES = [
  { value: 'allgemeinmedizin', label: 'Allgemeinmedizin' },
  { value: 'innere_medizin', label: 'Innere Medizin' },
  { value: 'kardiologie', label: 'Kardiologie' },
  { value: 'gastroenterologie', label: 'Gastroenterologie' },
  { value: 'endokrinologie', label: 'Endokrinologie / Diabetologie' },
  { value: 'nephrologie', label: 'Nephrologie' },
  { value: 'pneumologie', label: 'Pneumologie' },
  { value: 'rheumatologie', label: 'Rheumatologie' },
  { value: 'haematologie', label: 'Hämatologie / Onkologie' },
  { value: 'neurologie', label: 'Neurologie' },
  { value: 'psychiatrie', label: 'Psychiatrie / Psychotherapie' },
  { value: 'dermatologie', label: 'Dermatologie' },
  { value: 'gynaekologie', label: 'Gynäkologie' },
  { value: 'urologie', label: 'Urologie' },
  { value: 'orthopaedie', label: 'Orthopädie / Unfallchirurgie' },
  { value: 'chirurgie', label: 'Allgemeine Chirurgie' },
  { value: 'gefaesschirurgie', label: 'Gefäßchirurgie' },
  { value: 'herzchirurgie', label: 'Herzchirurgie' },
  { value: 'hno', label: 'HNO-Heilkunde' },
  { value: 'augenheilkunde', label: 'Augenheilkunde' },
  { value: 'paediatrie', label: 'Kinder- und Jugendmedizin' },
  { value: 'geriatrie', label: 'Geriatrie' },
  { value: 'sportmedizin', label: 'Sportmedizin' },
  { value: 'arbeitsmedizin', label: 'Arbeitsmedizin' },
  { value: 'naturheilkunde', label: 'Naturheilverfahren' },
  { value: 'ganzheitliche_medizin', label: 'Ganzheitliche Medizin' },
  { value: 'funktionelle_medizin', label: 'Funktionelle Medizin' },
  { value: 'praevention', label: 'Präventionsmedizin' },
  { value: 'nuklearmedizin', label: 'Nuklearmedizin' },
  { value: 'radiologie', label: 'Radiologie' },
  { value: 'anaesthesiologie', label: 'Anästhesiologie' },
  { value: 'pathologie', label: 'Pathologie' },
  { value: 'labormedizin', label: 'Labormedizin' },
  { value: 'mikrobiologie', label: 'Mikrobiologie' },
  { value: 'humangenetik', label: 'Humangenetik' },
  { value: 'palliativmedizin', label: 'Palliativmedizin' },
  { value: 'notfallmedizin', label: 'Notfallmedizin' },
  { value: 'tropenmedizin', label: 'Tropenmedizin / Reisemedizin' },
  { value: 'zahnarzt', label: 'Zahnmedizin' },
  { value: 'heilpraktiker', label: 'Heilpraktiker' },
  { value: 'sonstige', label: 'Sonstige' },
];
