-- Expanding hc_invoice table accommodating calculated metrics scaling globally automatically
ALTER TABLE hc_invoice ADD COLUMN IF NOT EXISTS invoice_number VARCHAR(50) DEFAULT NULL;
ALTER TABLE hc_invoice ADD COLUMN IF NOT EXISTS period_start DATE DEFAULT NULL;
ALTER TABLE hc_invoice ADD COLUMN IF NOT EXISTS period_end DATE DEFAULT NULL;
ALTER TABLE hc_invoice ADD COLUMN IF NOT EXISTS cases_count INTEGER DEFAULT 0;
ALTER TABLE hc_invoice ADD COLUMN IF NOT EXISTS org_fees_total DECIMAL(10,2) DEFAULT 0;
ALTER TABLE hc_invoice ADD COLUMN IF NOT EXISTS shipping_fees_total DECIMAL(10,2) DEFAULT 0;
ALTER TABLE hc_invoice ADD COLUMN IF NOT EXISTS subtotal DECIMAL(10,2) DEFAULT 0;
ALTER TABLE hc_invoice ADD COLUMN IF NOT EXISTS vat_amount DECIMAL(10,2) DEFAULT 0;
ALTER TABLE hc_invoice ADD COLUMN IF NOT EXISTS total_amount DECIMAL(10,2) DEFAULT 0;
ALTER TABLE hc_invoice ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'due';
ALTER TABLE hc_invoice ADD COLUMN IF NOT EXISTS due_date DATE DEFAULT NULL;
